### ISSUE TITLE
Buttons without background color

### ISSUE THREAD

**Issue by juandefelix** [Dominant7b9/cbf_middleman#4]
In some browsers (Safari), the "Request a Quote" and the "Contact" buttons don't have the expected background color. Looks like the correspondent `<a>` tags have an attribute `type=button`, that overrides the css coming from bootstrap. I think that attribute can be removed.

You can find them [here](https://github.com/Dominant7b9/cbf_middleman/blob/master/source/layouts/application/header.erb#L4), and [here](https://github.com/Dominant7b9/cbf_middleman/blob/80a10467c3fc1417fe385cd2b64e91dc3771ef1a/source/layouts/application/header.erb#L4)

**Comment by Dominant7b9** [comment]
Removed them, so it should be functioning properly now.
